### ISSUE TITLE
where is the long term maintain place? 

### ISSUE THREAD

**Issue by daqulazhang** [AKSW/openQA#2]
sorry, a little bit confused, this project was keeping progress in bitbucket.. now I find it in github..which place I should keep follow on it?

**Comment by edgardmarx** [comment]
The main source is and will stay in bitbuket http://bitbucket.org/emarx/openqa.
This mirror is been used by AKSW team and projects.

**Comment by daqulazhang** [comment]
ok, got it. btw, since you are here, may I take more time from you team, ask another question: about several weeks ago I saw yodaqa's owner peter was communicating with sirius group for integrating yodaqa into sirius and he claimed he is full time on project now and indeed they are really committing codes very frequently. from my point, the openqa architecture seems more mature I would like to start my work from here but I really want to know what's openqa's ambition and schedule?  I just jump into this area not for long, still not very familiar with details, sorry if I asked too straight..

**Comment by edgardmarx** [comment]
Sure,

openQA is a framework for QA development.
You can, for instance, compare it with other existing frameworks for document search as Lucene, SOLR and ElasticSearch.

Yoda is a nice try to build a QA system, like SINA (sina.aksw.org), HAWK and TBSL!

In another words, openQA is about give you support for development while the others give you the solution!

The new release of openQA will come with a very expected feature!
The ability to modulate better the query analysis and it should be available for download by October.

Hope is clear now!

best regards,
Edgard

**Comment by daqulazhang** [comment]
yes, thanks a lot:)
Can I  keep touch with you  for a more convenient way? Like instant message app or email, etc

**Comment by edgardmarx** [comment]
Yes,
add the following skype chat group,

https://join.skype.com/j2eVXaO

**Comment by daqulazhang** [comment]
Done！
